### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by abuu-u** [kartikk221/live-directory#10]
typo in: https://github.com/kartikk221/live-directory/blob/6ff9fe2a0f7e570240edda8d1b487155ddfc1e6c/types/components/LiveDirectory.d.ts#L39
should be `destroy`

**Comment by kartikk221** [comment]
Good catch, do you want to make a PR or should I fix and push a new version?

**Comment by abuu-u** [comment]
like this https://github.com/kartikk221/live-directory/pull/11 ?
