### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by ImLunaHey** [kartikk221/live-directory#2]
Would love to see types added for this. 👍

**Comment by kartikk221** [comment]
Hi, I'm actually currently in the process of writing 3.0.0 for LiveDirectory which will contain TypeScript types. LiveDirectory will also become a dependent of the upcoming `hyper-express-serve-static` internal middleware which will utilize LiveDirectory to power the static serving capabilities.

**Comment by ImLunaHey** [comment]
Saw your comment as I was opening the PR. Should I close the PR?

**Comment by kartikk221** [comment]
Yeah, feel free to close the PR for now
